platform :ios, '6.0'

pod 'AFNetworking', '1.2'
pod 'Facebook-iOS-SDK'
pod 'SSKeychain'
pod 'AttributedMarkdown', :git => 'https://github.com/dreamwieber/AttributedMarkdown.git'
pod 'GoogleAnalytics-iOS-SDK'
pod 'MBProgressHUD'
pod 'TestFlightSDK'
pod 'LAWalkthrough'
pod 'UrbanAirship-iOS-SDK'
pod 'SBJson'
pod 'Mixpanel'
pod 'NullSafe'
pod 'RHAddressBook'
pod 'JASidePanels'
pod 'NewRelicAgent'