platform :ios, '6.0'

pod 'AFNetworking'
pod 'Facebook-iOS-SDK'
pod 'SSKeychain'
pod 'AttributedMarkdown', :git => 'https://github.com/dreamwieber/AttributedMarkdown.git'
pod 'GoogleAnalytics-iOS-SDK'
pod 'MBProgressHUD'
pod 'SVPullToRefresh'
pod 'TestFlightSDK'
pod 'JSONKit'
pod 'LAWalkthrough'
pod 'UrbanAirship-iOS-SDK'